title: Projet
preset: page

fields:
  article_title:
    label: Titre
    type: writer
    inline: true

  cover:
    extends: fields/cover
    width: 2/3

  coverContrast:
    label: Contraste
    type: select
    width: 1/3
    required: true
    translate: false
    options:
      black: Noir
      white: Blanc

  isTranslated:
    label: État de la traduction
    type: toggle
    text:
      - Traduction imcomplète ou manquante
      - Traduction complète
    translate: false

  text: fields/blocks

pages: false
files:
  image:
    cover: true
