title: Projet

tabs:
  abstract:
    columns:
      left:
        width: 2/3
        fields:
          abstract:
            type: writer

          abstract_cover:
            extends: fields/cover
            help: "Redimensionnée au format {{ kirby.option('thumbs.presets.abstract.width') }}&times;{{ kirby.option('thumbs.presets.abstract.height') }}px (PNG)"

          year:
            label: Année
            type: text
            translate: false

          keywords:
            label: Mots-clefs
            type: tags

      right:
        width: 1/3
        sections:
          files: sections/files


  article:
    columns:
      left:
        width: 2/3
        fields:
          article_title:
            label: Titre
            type: writer
            inline: true

          article_cover:
            extends: fields/cover
            width: 2/3
            help: "Redimensionnée au format {{ kirby.option('thumbs.presets.cover.width') }}&times;{{ kirby.option('thumbs.presets.cover.height') }}px (PNG)"

          article_cover_contrast:
            label: Contraste
            type: select
            width: 1/3
            required: true
            translate: false
            options:
              black: Noir
              white: Blanc

          isTranslated:
            label: État de la traduction
            type: toggle
            text:
              - Traduction imcomplète ou manquante
              - Traduction complète
            translate: false

          text: fields/blocks

      right:
        width: 1/3
        sections:
          files: sections/files
