title: Site
preset: page

fields:
  cover:
    extends: fields/cover
    help: Utilisée pour le partage sur les réseaux sociaux

  description:
    label: Description du site
    help: Ce texte sera proposé à Google lors de l’indexation du site
    icon: code
    type: textarea
    inline: true
    buttons: false
    counter: true
    maxlength: 150
    spellcheck: true
  mail:
    label: Email
    type: email
    width: 1/2
    translate: false
  keywords:
    label: Mots-clefs
    icon: code
    type: tags
    width: 1/2

files:
  image:
    cover: true
pages:
  image: false
